### ISSUE TITLE
unable to pass Maps or objects to customfilters

### ISSUE THREAD

**Issue by vthadkamadla-mn** [HeavyHorst/remco#108]
Do we have support to pass JSON object in custom_filters, if i am passing string i can able to whatever i want with js script but i could not able to pass json object 
{%- set actual_properties = global_properties | extractConfig -%}
{{ actual_properties | toPrettyJSON}}
I can see actual_properties output properties same as global_properties when i just return, but i cannot able to parse the object of global_properties in  extractConfig it is just giving me null

**Comment by HeavyHorst** [comment]
Confirmed: custom JS filters can receive objects, not just strings.

A working example is:

`extractConfig.js`
```javascript
var input = In;

if (typeof input === "string") {
    input = JSON.parse(input);
}

input.app;
```

Template:
```django
{% set global_properties = '{"app":{"name":"demo","replicas":2},"meta":{"env":"test"}}' | parseJSON %}
{%- set actual_properties = global_properties | extractConfig -%}
{{ actual_properties | toPrettyJSON }}
```

Minimal config:
```toml
log_level = "debug"
log_format = "text"
filter_dir = "/path/to/filters"

[[resource]]
  [[resource.template]]
    src = "/path/to/example.tmpl"
    dst = "/tmp/output.json"

  [resource.backend]
    [resource.backend.file]
      onetime = true
      filepath = "./integration/file/config.yml"
      keys = ["/"]
```

Rendered output:
```json
{
    "name": "demo",
    "replicas": 2
}
```

The important part is that `In` is already an object after `parseJSON`, so `JSON.parse(In)` will fail. Use `In` directly when `typeof In === "object"`, and only call `JSON.parse()` when the input is actually a string.

I verified this locally against remco.
