### ISSUE TITLE
Accesing dictionary option not working as expected

### ISSUE THREAD

**Issue by freeseacher** [HeavyHorst/remco#40]
hi, i have such a template
```
{% set shard = printf("shard_%s", getenv("SHARD", 1)) %}
{% set config = getv("/shard_config") | parseYAML %}
{{ config.shard_1.machine }}
{% set shard_config = config.shard %}
{{ shard_config }}
```
And such key in consul
```
shard_1:
  machine: n1-standard-1
shard_2:
  machine: n1-standard-1
```

the problem is in last two lines of template, i'm expecting that will get data from `{{ config.shard_1.machine }}` but got empty string instead.
