### ISSUE TITLE
Looping over dict/object/map

### ISSUE THREAD

**Issue by JeffSpies** [HeavyHorst/remco#45]
This seems like a stupid question, but I didn't figure it out with confd, realized that the project was being deprecated, and still haven't figured it out with remco.

I have this in a yaml file:

```yaml
users:
  - name: admin
     hash: adminhash
  - name: user
    hash: userhash
```

What is the template code to get the following result:

```
admin adminhash
user userhash
```

I assumed it would be something like this:

```
  {% for user in gets("/users") %}
    {{user.name}} {{user.hash}}
  {% endfor %}
```

but I've tried quite a few template functions as variations of `gets` with no success.

Thanks!
