### ISSUE TITLE
Support the use of the `$` character in the config file

### ISSUE THREAD

**Issue by clinmanc** [HeavyHorst/remco#88]
As shown below, if the password contains the `$` character, the read password is `uhQhu4watyTgn$`, resulting in failure to connect to the redis

```toml
[[resource]]
name = "alertmanager"

  [resource.backend]
    [resource.backend.redis]
      nodes    = ["127.0.0.1:6379"]
      password = "uhQhu4watyTgn$Q$"
      prefix   = "/alert"
      interval = 5
      keys     = ["/*"]
```

The code that causes this problem

```golang
func readFileAndExpandEnv(path string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		return buf, errors.Wrap(err, "read file failed")
	}
	// expand the environment variables
	buf = []byte(os.ExpandEnv(string(buf)))
	return buf, nil
}
```

It can be fixed in the following way

[https://play.golang.org/p/JOJ7WLIUY3](https://go.dev/play/p/JOJ7WLIUY3)
