### ISSUE TITLE
With default backend config, all resources share the same backend config

### ISSUE THREAD

**Issue by tanguy-ortolo** [HeavyHorst/remco#94]
When a default configuration is provided for a given backend, it is actually used as a _single_ configuration, shared with _all_ resources the use that backend and that possibly reset its configuration values.

For instance, the following configuration sets default configuration for the file backend:

```toml
[default_backends.file]
    filepath = "data.yml"
```

The following resource does not _use_ that configuration as a default, but actually directly uses that configuration, setting its prefix and keys:

```toml
[[resource]]
    [[resource.template]]
        src = "info.tmpl"
        dst = "gondor.txt"
    
    [resource.backend.file]
        prefix = "/gondor"
        keys = [ "/" ]
```

Then, that second resource directly uses the same configuration, resetting its prefix and keys:

```toml
[[resource]]
    [[resource.template]]
        src = "info.tmpl"
        dst = "rohan.txt"
    
    [resource.backend.file]
        prefix = "/rohan"
        keys = [ "/" ]
```

After that, both resources use the same file backend configuration, with the prefix of `/rohan`, as set by the last parsed resource. Given the following data `data.yml`:

```yaml
gondor:
  name: Kingdom of Gondor
  king: Elessar
rohan:
  name: Riddermark of Rohan
  king: Eomer
```

and the following template `info.tmpl`:

```django
The king of {{ getv("/name") }} is {{ getv("/king") }}.
```

One would expect to get generated files `gondor.txt` and `rohan.txt` with distinct content. Instead, both file result with the same content:

```
The king of Riddermark of Rohan is Eomer.
```

The issue comes from `cmd/remco/config.go`, where backend configuration is parsed into an existing structure with pointers to existing default backend configuration. When no such default configuration exist, the TOML parser will allocate a new one, but when a default configuration exists, it is directly used without being copied, so all resources eventually end with a pointer to the same backend configuration.

I will be preparing a fix in a couple of days.
